### ISSUE TITLE
Error when handling resolver error

### ISSUE THREAD

**Issue by chess777** [yaacovCR/graphql-tools-fork#30]
On `graphql-tools-fork` v7.2.2 I get a following error:
```
ReferenceError: context is not defined
    at <Path>\node_modules\graphql-tools-fork\src\stitching\checkResultAndHandleErrors.ts:110:5
    at Array.map (<anonymous>)
    at handleList (<Path>\node_modules\graphql-tools-fork\src\stitching\checkResultAndHandleErrors.ts:104:15)
    at Object.handleResult (<Path>\node_modules\graphql-tools-fork\src\stitching\checkResultAndHandleErrors.ts:73:12)
    at defaultMergedResolver (<Path>\node_modules\graphql-tools-fork\src\stitching\defaultMergedResolver.ts:33:10)
    at field.resolve (<Path>\node_modules\graphql-tools-fork\src\stitching\mergeSchemas.ts:248:16)
    at field.resolve (<Path>\node_modules\graphql-extensions\src\index.ts:274:18)
    at resolveFieldValueOrError (<Path>\node_modules\graphql\execution\execute.js:467:18)
    at resolveField (<Path>\node_modules\graphql\execution\execute.js:434:16)
    at executeFields (<Path>\node_modules\graphql\execution\execute.js:275:18)
    at collectAndExecuteSubfields (<Path>\node_modules\graphql\execution\execute.js:713:10)
    at completeObjectValue (<Path>\node_modules\graphql\execution\execute.js:703:10)
    at completeValue (<Path>\node_modules\graphql\execution\execute.js:591:12)
    at completeValue (<Path>\node_modules\graphql\execution\execute.js:557:21)
    at <Path>\node_modules\graphql\execution\execute.js:492:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
Function `handleList` does not have `context` defined.

**Comment by yaacovCR** [comment]
Huh. Seems like my lint settings must be off!

**Comment by yaacovCR** [comment]
tslint thought it was the mocha context?

might be fixed by v7.2.3

**Comment by macrozone** [comment]
@yaacovCR same error happens on `8.5.0` but i just blindly replaced `graphql-tools` with `graphql-tools-fork` so there might be some breaking change that i did not see

**Comment by yaacovCR** [comment]
Can you include a stack trace?

**Comment by macrozone** [comment]
@yaacovCR on it.

buildDelegationTransforms is missing passing context. you should really fix your linter ;-)

**Comment by macrozone** [comment]
@yaacovCR https://github.com/yaacovCR/graphql-tools-fork/blob/master/src/stitching/delegateToSchema.ts#L94

**Comment by yaacovCR** [comment]
Lol, can you please submit PRs that fixes this issue and the linter/test setup.

Otherwise I can handle the first tonight, use v8.4.0 in the meantime, second I am not so sure how!

Thanks!
